{{- if .Values.dockerConfigAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: tonicai-build-writer-pull-secret
data:
  .dockerconfigjson: {{ .Values.dockerConfigAuth }}
type: kubernetes.io/dockerconfigjson
{{- end }}
