{{- range $key, $value := .Values.dataGenerationJobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $value.name }}
spec:
  schedule: "{{ $value.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ $value.name }}
            image: {{ $.Values.awsConfig.accountId }}.dkr.ecr.{{ $.Values.awsConfig.region }}.amazonaws.com/tonic-start-data-generation-job:v1.0.0-1
            imagePullPolicy: IfNotPresent
            env:
            - name: TONIC_API_KEY
              value: {{ $.Values.tonicApiKey }}
            - name: TONIC_API_HOST
              value: tonic-web-server
            - name: WORKSPACE_NAME
              value: {{ $value.workspace }}
          restartPolicy: OnFailure
---
{{- end }}
