{{- if eq (.Values.tonicai).is_local_k8s "true"  }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tonic-web-server-ingress
spec:
  defaultBackend:
    service:
      name: tonic-web-server
      port:
        number: 443
{{- end }}