apiVersion: v1
kind: Service
metadata:
  name: tonic-web-server
  namespace: {{ .Release.Namespace }}
{{- if  ((.Values.tonicai).web_server).annotations }}
  annotations:
    {{- toYaml .Values.tonicai.web_server.annotations | nindent 4 }}
{{- else }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
{{- end }}

  labels:
    app: tonic-web-server
spec:
  ports:
  - name: "https"
    port: 443
    targetPort: 443
# is_local_k8s currently only used by TIM
{{- if eq (.Values.tonicai).is_local_k8s true }}
  type: NodePort
{{- else }}
  type: LoadBalancer
{{- end }}
  selector:
    app: tonic-web-server
status:
  loadBalancer: {}
